### ISSUE TITLE
PlaySound errors

### ISSUE THREAD

**Issue by ssateneth** [spiralofhope/_DevPad.GUI#2]
Theres a fair chunk of PlaySound errors being thrown now because 7.3 removed the PlaySound function more or less. You can not select a sound by a string, you must play it by the soundkit ID.

**Comment by spiralofhope** [comment]
This should be easy to fix, but I'll probably end up removing any reference to this.

**Comment by ssateneth** [comment]
Took me about 5 minutes to fix, just had to change the references to the ones listed here. https://www.townlong-yak.com/framexml/ptr/SoundKitConstants.lua

They more or less have the same name, just capitals and underscores.

**Comment by spiralofhope** [comment]
Fixed in 7.3.0.1
