### ISSUE TITLE
Test for Classic compatibility

### ISSUE THREAD

**Issue by ssateneth** [spiralofhope/_DevPad.GUI#27]
will devpad be compatible with wow classic?

**Comment by spiralofhope** [comment]
I have no idea, I didn't get into the beta and I'm no longer subscribed; perhaps later.

**Comment by spiralofhope** [comment]
I have a subscription and have already fixed [TidyBar](https://github.com/spiralofhope/TidyBar) for compatibility.

There is a chance I can fix DevPad for classic.  I opened #28 for that effort, and will now close this one to keep things tidy.
